GET http://localhost:8888/users

###
POST http://localhost:8888/user
Content-Type: application/json

{
  "name": "Vinicius Dias",
  "email": "vinicius.dias@gmail.com",
  "password": "Vinicius321@"
}

###

PUT http://localhost:8888/user/b64aebc8-9a27-4e32-bcb6-52c9335fdc53
Content-Type: application/json

{
  "name": "Vinicius Dias11",
  "email": "vinicius.dias@gmail.com",
  "password": "DiasVini321@"
}

### 
DELETE http://localhost:8888/user/b64aebc8-9a27-4e32-bcb6-52c9335fdc53