GET http://localhost:8888/users

###
POST http://localhost:8888/user
Content-Type: application/json

{
  "name": "Vinicius Dias",
  "email": "vinicius.dias@gmail.com",
  "password": "Vinicius321@"
}

###

PUT http://localhost:8888/user/5225fb4e-d0f0-483f-b270-456e401d3a4f
Content-Type: application/json

{
  "name": "Vinicius Dias11",
  "email": "vinicius.dias@gmail.com",
  "password": "DiasVini321@"
}

### 
DELETE http://localhost:8888/user/5225fb4e-d0f0-483f-b270-456e401d3a4f